#!/bin/bash
# Environment Setup Script - Production + Dev Containers Only

echo "🚀 Simplified Environment Setup"
echo ""
echo "✅ This project uses:"
echo "   📦 Docker Compose for production deployment"
echo "   🔧 Dev Containers for development"
echo ""
echo "For Development:"
echo "  1. Open project in VS Code"
echo "  2. Command Palette: 'Dev Containers: Reopen in Container'"
echo "  3. Environment automatically configured"
echo ""
echo "For Production:"
echo "  # Set environment variables:"
echo "  export COMPOSE_PROJECT_NAME=my-project"
echo "  export DB_PASSWORD=secure_password"
echo "  export SECRET_KEY=super_secret_jwt_key"
echo ""
echo "  # Deploy with nginx (secure):"
echo "  docker-compose --profile production up -d"
echo ""
echo "  # Or deploy API only:"
echo "  docker-compose up -d"
echo ""
echo "📝 Configuration:"
echo "  - Production: docker-compose.yml"
echo "  - Development: .devcontainer/"
echo ""
echo "🔒 Security:"
echo "  - Production: Only nginx exposed (port 80/443)"
echo "  - Development: Isolated in dev containers"
