name: Build, Push, and Scan Docker Image

on:
  push:
    branches: [main]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Get short commit SHA
      id: vars
      run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: mangale/fast-api:${{ env.SHORT_SHA }}

    - name: Scan Docker image with Trivy
      run: |
        trivy image --format table --output trivy-report.txt mangale/fast-api:${{ env.SHORT_SHA }}

    - name: Send Trivy Report via Email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "🚨 Trivy Vulnerability Report for mangale/fast-api:${{ env.SHORT_SHA }}"
        to: lopchanmangal5@gmail.com
        from: "GitHub Actions <${{ secrets.EMAIL_USERNAME }}>"
        body: |
          Hello,

          Please find attached the vulnerability report for the image:
          mangale/fast-api:${{ env.SHORT_SHA }}

          Regards,
          GitHub Actions
        attachments: trivy-report.txt
